### ISSUE TITLE
Service Now Connector Configuration: tagging values

### ISSUE THREAD

**Issue by deloitte-lza-test** [aws-samples/aws-service-management-connector#2]
"Hello,

We are trying to use AWS SM Connector with ServiceNow for one of our clients, and we have some questions.

We need to have field validation (length, characters) as well as auto-populating variables with data directly from the ServiceNow. 

How can we get ServiceNow to interact with the Service Catalog items to define form fields, and allowed values?

At the moment, only option for interacting from ServiceNow with AWS Catalog Item is to use “Automated Tags” that are simple, non-scriptable table references.

How can we get and edit the form field values as they are not standard variables, and presumable is not a standard ServiceNow’s internal GlideForm (g_form) API call?" 

The field values are all masked as it is.

Additionally we are wondering about invoking service catalogue items via a script, with an example such as below;

"var cartId = GlideGuid.generate(null);
var cart = new Cart(cartId);
 //add your requested item to the cart by sys_id of the catalog item
var item = cart.addItem('4054428fdb151f0097679ec6db9619c0', 1);

//fill in the variables on the request item form
cart.setVariable(item,"u_requested_for", "e80edd6edbec6bc097275e25ca9619a4"); 
cart.setVariable(item,"contact_number", "0");
cart.setVariable(item,"assignment_group", "87ec1c342b2e71406c487fb5a8da1524"); 
cart.setVariable(item,"application_service", "cdedfbcedb0f9744c291c170ba9619a7");
cart.setVariable(item,"short_description", email.subject);
cart.setVariable(item,"description", email.body_text);
var rc = cart.placeOrder();"

The question is, how do we pass the values to the ProvisioningParameters variable, that operates as a dropdown and dynamically contains all variables coming from AWS?

Cheers

**Comment by mjoethom** [comment]
Hi,

Thanks for reaching out. The issue mentioned above is not directly related to the solution provided for automation in the github repo. We have received your request internally through the Support channel and are looking into it. For any further questions on the AWS Service Management Connector, please reach out to aws-servicemanagement-connector@amazon.com
